apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: proxy-autoscale
  labels:
    app: proxy
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: proxy-deployment
  maxReplicas: 5
  minReplicas: 1
