# This is a sample production config (to be deployed in the WEB-INF directory).
# This is the same as what Google Registry runs in production, except with
# placeholders for Google-specific settings.

appEngine:
  projectId: placeholder

gSuite:
  domainName: placeholder
  outgoingEmailDisplayName: placeholder
  outgoingEmailAddress: placeholder
  adminAccountEmailAddress: placeholder

registryPolicy:
  contactAndHostRoidSuffix: placeholder
  productName: placeholder
  registrarChangesNotificationEmailAddresses:
    - placeholder
    - placeholder
  defaultRegistrarWhoisServer: placeholder
  defaultRegistrarReferralUrl: placeholder
  tmchCaMode: PRODUCTION
  tmchCrlUrl: http://crl.icann.org/tmch.crl
  tmchMarksDbUrl: https://ry.marksdb.org

rde:
  reportUrlPrefix: https://ry-api.icann.org/report/registry-escrow-report
  uploadUrl: sftp://placeholder@sftpipm2.ironmountain.com/Outbox

registrarConsole:
  logoFilename: placeholder
  supportPhoneNumber: placeholder
  supportEmailAddress: placeholder
  announcementsEmailAddress: placeholder
  integrationEmailAddress: placeholder
  technicalDocsUrl: https://drive.google.com/drive/folders/placeholder

misc:
  sheetExportId: placeholder
